language: php
php:
  - 5.4
  - 5.5

branches:
  only:
    - master
    - dev

matrix:
  fast_finish: true

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # ---------------------
  # Setup DB
  # ---------------------
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e 'create database drupal;'

  # ---------------------
  # Install Drush
  # ---------------------
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:dev-master

before_script:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # ---------------------
  # Variables
  # ---------------------
  - export DIR=`pwd`'/'
  - cd ../../
  - export ROOT=`pwd`'/'

  # ---------------------
  # Create central git repository
  # ---------------------
  - git clone --single-branch --branch=7.x https://github.com/drupal/drupal.git $ROOT/drupal-origin
  - echo v1 > foo.txt
  - git add foo.txt
  - git commit -m 'First version for foo.txt'

  # ---------------------
  # Git for Drupal instances
  # ---------------------
  - git clone $ROOT/drupal-origin $ROOT/drupal-production/
  - git clone $ROOT/drupal-origin $ROOT/drupal-staging/

  # ---------------------
  # Make change for origin repository, will check git pull later in a test case
  # ---------------------
  - cd $ROOT/drupal-origin
  - echo v2 > foo.txt
  - git commit foo.txt -m "New version for foo.txt"

  # ---------------------
  # Install the production & staging sites
  # ---------------------
  - cd $ROOT/drupal-production/
  - drush si -y --db-prefix=production_ --db-url=mysql://root:@localhost/drupal
  - drush run-server --server=builtin 127.0.0.1:8989 &
  - cd $ROOT/drupal-staging/
  - drush si -y --db-prefix=staging_ --db-url=mysql://root:@localhost/drupal
  - drush run-server --server=builtin 127.0.0.1:8990 &

  # ---------------------
  # Install the drupal deploy instance
  # ---------------------
  - cd $DIR
  - composer install --dev
  - cp config.sample.php config.php
  - php -S localhost:8991 -t $DIR/public/ $DIR/public/index.php &

script: phpunit

notifications:
  email: false
